# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Us
    url: about
    weight: 20
  - name: Events
    url: events
    weight: 30
  - name: Courses/Upskill
    url: courses
    weight: 40
  - name: Find Expert
    url: expert
    weight: 50
  - name: Codes
    url: code
    weight: 55
  - name: Contact Us
    url: contact
    weight: 60
  - name: Content
    url: projects
    weight: 60